<?php
    // Load your extra extensions here...
?>
            <div id="root" class="page">
                <div class="content">
                    <?php UTIL::Load_Content('root', 'dynamic'); ?>
                    <div class="controls">
                        <br>
                        <div class="control_item">
                            <a id="index_button" class="button" href="test">
                                <?=UTIL::Load_Content('go_to_button_text', 'static');?>
                            </a>
                        </div>
                    </div>
                </div>
            </div>

<script>
    var utils = new vulcan();

    utils.system.require('/framework/mvc/views/assets/js', 'root');
</script>
