<?
    UTIL::Load_Extension('content_fetcher', 'js');
?>
            <div id="root" class="page">
                <div class="content">
                    <?UTIL::Load_File('root');?>
                    <div class="controls">
                        <br>
                        <div class="control_item">
                            <a id="index_button" class="button" href="test">
                                <?UTIL::Load_File('go_to_button_text');?>
                            </a>
                        </div>
                    </div>
                </div>
            </div>

<script>
    ultron(function(event)
           {
                
           });
</script>
