<?
    UTIL::Load_Extension('vulcan', 'js');
    UTIL::Load_Extension('ultron', 'js');
?>
            <div id="root" class="page">
                <div class="content">
                    <?UTIL::Load_Content('root', 'dynamic');?>
                    <div class="controls">
                        <br>
                        <div class="control_item">
                            <a id="index_button" class="button" href="test">
                                <?=UTIL::Load_Content('go_to_button_text', 'static');?>
                            </a>
                        </div>
                    </div>
                </div>
            </div>

<script>
    ultron(function(event)
           {
                
           });
</script>
