<?php
    UTIL::Load_Extension('yoda', 'js');
    UTIL::Load_Extension('stopwatch', 'js');
    UTIL::Load_Extension('heartbeat', 'js');
    UTIL::Load_Extension('msgbox', 'js');
    UTIL::Load_Extension('workbox', 'js');
    UTIL::Load_Extension('key_manager', 'js');
    UTIL::Load_Extension('keycard', 'php');
    UTIL::Load_Extension('regy', 'php');
    UTIL::Load_Extension('ra', 'php');

    if (!empty($_POST))
    {
        $post_data = $_POST;

        $_POST = null;
    }

    // Uncomment to test the RA ORM (MySQL or MSSQL running service is required)
    /*
    $RA = new RA();
    $result = $RA::ORM('my')    // MySQL: "my" / MSSQL: "ms"
              ->Initialize('root', '', 'localhost')
              ->Use_DB_Model('test_odb')
              ->Save_DB()
              ->Use_Table_Model('test_table_1')
              ->New_Model_Property('Surname', 'Smith')
              ->Delete_Model_Property('name')
              ->Save_Table('test_table_1')
              ->Use_Table_Model('test_table_2')
              ->New_Model_Property('Surname', 'Stalone')
              ->Edit_Model_Property('Surname', 'Statham')
              ->Save_Table('test_table_2')
              ->Result();
    */
?>
            <div id="test" class="page">
                <div class="content">
                    <?
                        UTIL::Load_Content('test', 'dynamic');

                        echo '<br><br>';
                        echo MVC::Restore_Content('test');
                    ?>
                    <div class="controls">
                        <div id="test_data">
                            <br>
                            <div id="test_elements">
                                <?
                                    $splash = new SPLASH();

                                    $test_text = UTIL::Load_Content('test_button_text', 'static');

                                    echo '<div id="left_elements">';
                                    echo '<div class="control_item">';
                                    echo $splash->Button('create', array('value'    =>  $test_text . ' (AJAX request)',
                                                                         'type'     =>  'button',
                                                                         'class'    =>  'button button_alt'),
                                                                   array('onclick'  => 'ajax_fetch_content(\'motto\')'));
                                    echo '</div>';
                                    //print_r($splash->Button('debug', array('value', 'id'), array('onclick')));

                                    echo '<div class="control_item">';
                                    echo $splash->Button('create', array('value'    =>  $test_text . ' (AJAX response)',
                                                                         'type'     =>  'button',
                                                                         'class'    =>  'button button_alt'),
                                                                   array('onajaxserverclick' => 
                                                                   array('Server_Mouse_Click(' .  UTIL::Load_Content('hello', 'static') . ' micro-MVC! (AJAX response))', 
                                                                         'test_results')));
                                    echo '</div>';
                                    //print_r($splash->Button('debug', array('value', 'id'), array('onajaxserverclick')));

                                    echo '<div class="control_item">';
                                    echo $splash->Button('create', array('value'    =>  $test_text . ' (Form post)',
                                                                         'type'     =>  'button',
                                                                         'class'    =>  'button button_alt'),
                                                                   array('onserverclick'     => 
                                                                   array('Server_Mouse_Click(' .  UTIL::Load_Content('hello', 'static') . ' micro-MVC! (Form post))', 
                                                                         '../test/')));
                                    echo '</div>';
                                    //print_r($splash->Button('debug', array('value', 'id'), array('onserverclick')));

                                    echo '<br><div class="control_item">';
                                    echo $splash->Button('create', array('value'    =>  $test_text . ' (Login form)',
                                                                         'type'     =>  'button',
                                                                         'class'    =>  'button button_alt'),
                                                                   array('onclick'  =>  'show_login_box()'));
                                    echo '</div>';
                                    //print_r($splash->Button('debug', array('value', 'id'), array('onclick')));

                                    echo '<div class="control_item">';
                                    echo $splash->Button('create', array('value'    =>  $test_text . ' (Registration form)',
                                                                         'type'     =>  'button',
                                                                         'class'    =>  'button button_alt'),
                                                                   array('onclick'  =>  'show_register_box()'));
                                    echo '</div>';
                                    //print_r($splash->Button('debug', array('value', 'id'), array('onclick')));
                                    echo '</div>';

                                    echo '<div id="right_elements">';
                                    echo '<div class="control_item">
                                          <input id="file_input" name="file" type="file" class="button" required>
                                          </div>';
                                    echo '<div class="control_item" style="margin-bottom: 44px;">';
                                    echo $splash->Button('create', array('value'    =>  $test_text . ' (AJAX file post)',
                                                                         'type'     =>  'button',
                                                                         'class'    =>  'button'),
                                                                   array('onclick'  =>  'send_data_to_server()'));
                                    echo '</div>';
                                    //print_r($splash->Button('debug', array('value', 'id'), array('onclick')));

                                    echo '<br><div class="control_item">';
                                    echo $splash->Button('create', array('value'    =>  $test_text . ' (Logout button)',
                                                                         'type'     =>  'button',
                                                                         'class'    =>  'button button_alt'),
                                                                   array('onclick'  =>  'logout()'));
                                    echo '</div>';
                                    //print_r($splash->Button('debug', array('value', 'id'), array('onclick')));

                                    echo '<div class="control_item">';
                                    echo $splash->Button('create', array('value'    =>  $test_text . ' (Send email)',
                                                                         'type'     =>  'button',
                                                                         'class'    =>  'button button_alt'),
                                                                   array('onclick'  =>  'send_email()'));
                                    echo '</div>';
                                    //print_r($splash->Button('debug', array('value', 'id'), array('onclick')));
                                    echo '</div>';
                                ?>
                            </div>
                            <br>
                            <div id="test_results" class="note">
                            <?
                                if (isset($post_data))
                                {
                                    if (!empty($post_data['splash_post_result']))
                                        echo $post_data['splash_post_result'];
                                    else
                                    {
                                        $searches = array('{message}');
                                        $replaces = array(print_r($post_data, true));
                                        $arguments = array($searches, $replaces);
                                        $info_template = UTIL::Fetch_Template('info', $arguments);

                                        echo $info_template;
                                    }
                                }
                            ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

<script>
    var utils = new vulcan();
    var local_labels = new yoda();
    var classic_ajax = new bull();
    var new_ajax = new taurus();
    var work_box = new workbox();
    var key_card = new keycard();
    var regy_form = new regy();

    var m_mvc_dynamic_contents = {
                                    "en" : [
                                                { "m_mvc"               :   "micro-MVC" },
                                                { "close_button"        :   "Close" },
                                                { "email_inv"           :   "The e-mail format is invalid!" },
                                                { "credentials_cmplx"   :   "Please choose more complex credentials!" },
                                                { "credentials_inv"     :   "Credentials are invalid!" },
                                                { "credentials_wrg"     :   "Your credentials are wrong!" },
                                                { "passwd_confirm"      :   "Password confirmation failed!" },
                                                { "session_lost"        :   "Your session has been terminated!" },
                                                { "reg_success"         :   "Registration succeeded!" },
                                                { "reg_fail"            :   "Registration failed!" },
                                                { "logout_error"        :   "Logout was impossible!" }
                                           ],
                                    "gr" : [
                                                { "m_mvc"               :   "micro-MVC" },
                                                { "close_button"        :   "Κλείσε" },
                                                { "email_inv"           :   "Μη έγκυρο e-mail!" },
                                                { "credentials_cmplx"   :   "Παρακαλώ επιλέξτε πιο σύνθετα στοιχεία πρόσβασης!" },
                                                { "credentials_inv"     :   "Τα στοιχεία πρόσβασης είναι άκυρα!" },
                                                { "credentials_wrg"     :   "Τα στοιχεία πρόσβασης είναι λάθος!" },
                                                { "passwd_confirm"      :   "Αποτυχία επαλήθευσης πεδίου κωδικού!" },
                                                { "session_lost"        :   "Διεκόπη η σύνδεση με το σύστημα!" },
                                                { "reg_success"         :   "Η εγγραφή ήταν επιτυχής!" },
                                                { "reg_fail"            :   "Η εγγραφή ήταν ανεπιτυχής!" },
                                                { "logout_error"        :   "Δεν ήταν δυνατή η αποσύνδεση!" },
                                           ]
                                 };

    // Progammatic way to create the JSON config above
    /*
    local_labels.init(['en', 'gr']);
    m_mvc_dynamic_contents = local_labels.set(m_mvc_dynamic_contents, 'en', { "m_mvc" : "micro-MVC" });
    m_mvc_dynamic_contents = local_labels.set(m_mvc_dynamic_contents, 'en', { "close" : "Close" });
    m_mvc_dynamic_contents = local_labels.set(m_mvc_dynamic_contents, 'en', { "email_inv" : "The email format is invalid!" });
    m_mvc_dynamic_contents = local_labels.set(m_mvc_dynamic_contents, 'en', { "credentials_cmplx" : "Please choose more complex credentials!" });
    m_mvc_dynamic_contents = local_labels.set(m_mvc_dynamic_contents, 'en', { "credentials_inv" : "Credentials are invalid!" });
    m_mvc_dynamic_contents = local_labels.set(m_mvc_dynamic_contents, 'en', { "credentials_wrg" : "Your credentials are wrong!" });
    m_mvc_dynamic_contents = local_labels.set(m_mvc_dynamic_contents, 'en', { "passwd_confirm" : "Password confirmation failed!" });
    m_mvc_dynamic_contents = local_labels.set(m_mvc_dynamic_contents, 'en', { "session_lost" : "Your session has been terminated!" });
    m_mvc_dynamic_contents = local_labels.set(m_mvc_dynamic_contents, 'en', { "reg_success" : "Registration succeeded!" });
    m_mvc_dynamic_contents = local_labels.set(m_mvc_dynamic_contents, 'en', { "reg_fail" : "Registration failed!" });
    m_mvc_dynamic_contents = local_labels.set(m_mvc_dynamic_contents, 'en', { "logout_error" : "Logout was impossible!" });
    m_mvc_dynamic_contents = local_labels.set(m_mvc_dynamic_contents, 'gr', { "m_mvc" : "micro-MVC" });
    m_mvc_dynamic_contents = local_labels.set(m_mvc_dynamic_contents, 'gr', { "close" : "Κλείσε" });
    m_mvc_dynamic_contents = local_labels.set(m_mvc_dynamic_contents, 'gr', { "email_inv" : "Μη έγκυρο e-mail!" });
    m_mvc_dynamic_contents = local_labels.set(m_mvc_dynamic_contents, 'gr', { "credentials_cmplx" : "Παρακαλώ επιλέξτε πιο σύνθετα στοιχεία πρόσβασης!" });
    m_mvc_dynamic_contents = local_labels.set(m_mvc_dynamic_contents, 'gr', { "credentials_inv" : "Τα στοιχεία πρόσβασης είναι άκυρα!" });
    m_mvc_dynamic_contents = local_labels.set(m_mvc_dynamic_contents, 'gr', { "credentials_wrg" : "Τα στοιχεία πρόσβασης είναι λάθος!" });
    m_mvc_dynamic_contents = local_labels.set(m_mvc_dynamic_contents, 'gr', { "passwd_confirm" : "Αποτυχία επαλήθευσης πεδίου κωδικού!" });
    m_mvc_dynamic_contents = local_labels.set(m_mvc_dynamic_contents, 'gr', { "session_lost" : "Διεκόπη η σύνδεση με το σύστημα!" });
    m_mvc_dynamic_contents = local_labels.set(m_mvc_dynamic_contents, 'gr', { "reg_success" : "Η εγγραφή ήταν επιτυχής!" });
    m_mvc_dynamic_contents = local_labels.set(m_mvc_dynamic_contents, 'gr', { "reg_fail" : "Η εγγραφή ήταν ανεπιτυχής!" });
    m_mvc_dynamic_contents = local_labels.set(m_mvc_dynamic_contents, 'gr', { "logout_error" : "Δεν ήταν δυνατή η αποσύνδεση!" });
    */

    var m_mvc = local_labels.fetch(m_mvc_dynamic_contents, utils.misc.active_language(), 'm_mvc');
    var close_button = local_labels.fetch(m_mvc_dynamic_contents, utils.misc.active_language(), 'close_button');

    work_box.init('main', m_mvc, close_button);

    function ajax_fetch_content(content_id)
    {
        var msg_box = new msgbox();

        msg_box.init('main');

        content_fetcher(content_id, '<?=LANG::Get('this');?>', 
        function(response) { msg_box.show('micro-MVC', response); }, 
        function() {}, 
        function() {});
    }

    function send_data_to_server()
    {
        var file_input_element = utils.objects.by_id('file_input');
        var form_data = new FormData();

        form_data.append('test_file', file_input_element.files[0]);

        var ajax_config = {
                                "type"                  :   "data",
                                "url"                   :   "/framework/mvc/views/assets/php/ajax_test.php",
                                "data"                  :   form_data,
                                "element_id"            :   "test_results",
                                "content_fill_mode"     :   "replace"
                          };

        classic_ajax.run(ajax_config);
    }

    <?
        if (!isset($post_data))
        {
    ?>
            var ajax_config = {
                                    "type"                  :   "data",
                                    "url"                   :   "/framework/mvc/views/assets/php/ajax_test.php",
                                    "data"                  :   "ajax_check=1",
                                    "element_id"            :   "test_results",
                                    "content_fill_mode"     :   "replace"
                              };

            classic_ajax.run(ajax_config);
    <?
        }

        unset($post_data);
    ?>

    function show_login_box()
    {
        var login_form = '<?=KeyCard::Show_Login_Form();?>';

        blur_screen('show');

        work_box.show(login_form, null, function() { blur_screen('hide'); });

        key_card.init('login');
    }

    function show_register_box()
    {
        var register_form = '<?=Regy::Show_Form();?>';

        blur_screen('show');

        work_box.show(register_form, null, function() { blur_screen('hide'); });

        regy_form.init();
    }

    function logout()
    {
        var logout_button = '<?=KeyCard::Show_Logout_Button();?>';

        blur_screen('show');

        work_box.show(logout_button, null, function() { blur_screen('hide'); });

        key_card.init('logout');
    }

    function send_email()
    {
        var data = 'gate=send_email&send=1&email=test@testdomain.com';

        ajax_factory(data, function(response)
                           {
                                utils.objects.by_id('test_results').innerHTML = response;

                                console.log('[Woody]')
                                console.log('OK');
                                console.log('');
                           },
                           function()
                           {
                                // Nothing to do...
                           },
                           function()
                           {
                                // Nothing to do...
                           });
    }

    // *** Either use this function when logged-in to avoid session hijacking or utilize Anti-Hijack extension straight from PHP ***
    function hijack_protection()
    {
        var data = 'gate=hijack_protection';

        ajax_factory(data, function(response)
                           {
                                console.log('[Anti-Hijack]')
                                console.log(response);
                                console.log('');
                           },
                           function()
                           {
                                location.assign('/');
                           },
                           function()
                           {
                               // Nothing to do...
                           });
    }

    function blur_screen(mode)
    {
        var main_body = utils.objects.by_id('test');

        if (mode === 'show')
            main_body.style.filter = 'blur(8px)';
        else
            main_body.style.filter = 'none';
    }

    utils.system.require('/framework/mvc/views/assets/js', 'test');
</script>
