<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="Cache-control" content="public">
        <meta name="robots" content="index, follow">
        <meta name="description" content="micro-MVC :: The little-BIG framework">
        <meta name="keywords" content="web,framework,fast,secure,simple">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="icon" type="image/png" href="/site/pix/micro_mvc_icon.png">
        <link rel="stylesheet" href="/site/css/main.css">
        <title><?=UTIL::Load_Content('title', 'static');?></title>
    </head>
    <body>
        <div id="main">
        <?php
            UTIL::Load_Section('header');
            
            $this_route = MVC::Get_Route('this');
            
            if ($this_route === false)
                require('framework/errors/404.phtml');
            else
            {
                if ($this_route === 'root')
                    MVC::Go_To($this_route);
                else
                {
                    $args = '';
                    
                    MVC::Go_To($this_route, $args);
                }
            }
            
            unset($this_route);
            
            UTIL::Load_Section('footer');
        ?>
            <script src="/site/js/main.js"></script>
        </div>
    </body>
</html>
