<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <link rel="icon" type="image/png" href="/site/pix/micro_mvc_icon.png">
        <link rel="stylesheet" href="/site/main.css">
        <title><?UTIL::Load_File('title');?></title>
    </head>
    <body>
        <div id="main">
        <?
            require('sections/header.phtml');
            
            $this_route = UTIL::Get_Variable('this_route');

            if ($this_route === 'root')
                MVC::Go_To($this_route);
            else
            {
                if (!in_array($this_route, UTIL::Get_Variable('all_routes')))
                    require('framework/errors/404.phtml');
                else
                {
                    $args = '';
                    
                    MVC::Go_To($this_route, $args);
                }
            }

            unset($this_route);

            require('sections/footer.phtml');
        ?>
        </div>
    </body>
</html>
