                <div id="header">
                	<?UTIL::Load_Section('languages');?>
                    <div class="logo">
                        <a href="/<?=LANG::Get('this');?>/" title="<?=UTIL::Load_Content('mouse_tag', 'static');?>">
                            <img src="/site/pix/micro_mvc.png" alt="micro-MVC Logo">
                        </a>
                    </div>
                    <div class="motto"><?=UTIL::Load_Content('motto', 'static');?></div>
                </div>
