                <div id="header">
                	<?require('languages.phtml');?>
                    <div class="logo">
                        <a href="/<?=UTIL::Get_Variable('this_lang');?>/" title="<?UTIL::Load_File('mouse_tag');?>">
                            <img src="/site/pix/micro_mvc.png">
                        </a>
                    </div>
                    <div class="motto"><?UTIL::Load_File('motto');?></div>
                </div>
