		            <div id="languages">
		            	<?
		            		$my_route = UTIL::Denormalize_Route(MVC::Get_Route('this', '*'));

		            		if ($my_route === 'root')
		            			$my_route = '';

							$all_langs = UTIL::Get_Variable('all_langs');

		            		foreach ($all_langs as $index => $language)
		            		{
		            			if ($language === UTIL::Get_Variable('this_lang'))
		            				$active = 'active_language';
		            			else
		            				$active = '';

		            			echo '<a href="/'. $language . '/' . 
		            							   $my_route . '" class="' . 
		            							   $active . '">' . 
		            							   strtoupper($language) . '</a>';

		            			if ($index < (count(UTIL::Get_Variable('all_langs')) - 1))
		            				echo ' | ';
		            		}
		            	?>
		            </div>
