<div id="login_control" class="page">
    <div class="content">
        <center>{login}</center>
        <div class="controls">
            <br>
            <div class="control_item">
                <input id="login_username_text" class="text" placeholder="Please enter your e-mail...">
            </div>
            <div class="control_item">
                <input id="login_password_text" class="text" type="password" placeholder="Please enter your password...">
            </div>
            <br>
            <div class="control_item">
                <button id="login_button" class="button">
                    {login_button_text}
                </button>
            </div>
        </div>
    </div>
</div>
