<div id="registration_control" class="page">
    <div class="content">
        <center>{register}</center>
        <div class="controls">
            <br>
            <div class="control_item">
                <input id="register_username_text" class="text" placeholder="Please enter an e-mail...">
            </div>
            <div class="control_item">
                <input id="register_password_text" class="text" type="password" placeholder="Please enter a password...">
            </div>
            <div class="control_item">
                <input id="register_password_confirm_text" class="text" type="password" placeholder="Please confirm password...">
            </div>
            <br>
            <div class="control_item">
                <button id="register_button" class="button">
                    {register_button_text}
                </button>
            </div>
        </div>
    </div>
</div>
