Welcome to micro-MVC!
<br><br>
micro-MVC is an agile, small, productive and robust MVC framework for PHP with integrated JS utilities and AJAX support.
<br><br>
Please take your time and play with the framework to understand its potential.
If you have any problems, something to note or if you just found a bug then 
<a href="mailto:g.delaportas@gmail.com?subject=micro-MVC&body=Hi George, how are you?">get in touch</a> 
with the creator.
<br><br>
Enjoy!
